export const appState = {
    copyText: '',
    copyMarkdown: '',
    currentCommandId: null,
    controlState: {
        availableProviders: [],
        availableModels: [],
        selectedProvider: '',
        selectedModel: '',
        thinkEnabled: false,
    },
    localizedStrings: {
        provider_label: 'Provider',
        model_label: 'Model',
        think_mode_label: 'Think mode',
        attach_button: 'Attach',
        send_button: 'Send',
        copy_text_button: 'Copy text',
        copy_markdown_button: 'Copy markdown',
        copy_response_button: 'Copy response',
        copy_response_markdown_button: 'Copy response markdown',
        copy_table_button: 'Copy table',
        clear_button: 'Clear',
        close_button: 'Close',
        chat_placeholder: 'Type your message...',
        waiting_status: 'Waiting for host command...',
        no_content: 'No content available.',
        no_chat_messages: 'No chat messages available.',
        thinking_label: 'Thinking',
        thinking_trace_label: 'Thinking trace',
        remove_attachment: 'Remove',
        attachment_fallback_name: 'Attachment',
        initial_image_name: 'Initial image',
        image_attachment_notice: '[Image attachment included]',
        submitted_status: 'Message submitted.',
        attach_failed_status: 'Unable to attach file.',
        content_cleared_status: 'Content cleared.',
        copied_status: 'Copied to clipboard.',
        copy_failed_status: 'Copy failed.',
        unknown_schema_status: 'Unknown host schema.',
        unsupported_protocol_status: 'Unsupported host protocol version.',
        unknown_message_type_status: 'Unknown host message type.',
        parse_host_message_failed_status: 'Unable to parse host message.',
        apply_host_command_failed_status: 'Unable to apply host command.',
        bridge_unavailable_status: 'WebView bridge unavailable.',
        window_closed_message: 'Window closed by host command.',
        error_prefix: 'Error',
        progress_prefix: 'Progress',
        progress_default_message: 'Working...',
        command_prefix: 'Command',
        unhandled_command_prefix: 'Unhandled command',
        result_action_fallback_label: 'Action',
    },
    chatState: {
        active: false,
        commandId: null,
        conversationId: null,
        messages: [],
        attachments: [],
    },
    displayState: {
        blocks: [],
        actions: [],
    },
    viewState: {
        mode: 'display',
    },
};
