# -*- coding: utf-8 -*-
from __future__ import annotations

from .collectors import ImageContextCollector, ExtractionStructureCollector, ExtractionTextCollector
from .extractors import (
	BrowserAwarePageExtractor,
	BrowserCandidateProvider,
	CandidateProvider,
	CandidateExtractionContext,
	GenericCandidateProvider,
	PageExtractionError,
	TerminalCandidateProvider,
	TextEditorCandidateProvider,
	TextAppCandidateProvider,
	buildDefaultCandidateProviders,
)
from .pipeline import ContextPipeline
from .protocols import (
	ContextCollector,
	ContextFragment,
	PageContextFragment,
	BrowserContextFragment,
	TerminalContextFragment,
	ImageContextFragment,
)
from .prompts import (
	build_chat_messages,
	build_image_description_prompt,
	build_extraction_summary_prompt,
	build_system_prompt_for_nvda_assistant,
)
from .types import (
	ALL_STRUCTURED_FIELDS,
	ContentRequest,
	ExtractionFacts,
	ExtractionIntent,
	ExtractionResult,
	ExtractionSnapshot,
	ExtractionStructure,
	FocusedElementImageRequest,
	FocusedElementTextRequest,
	ForegroundImageRequest,
	ImageCaptureSource,
	ImageContext,
	NavigatorImageRequest,
	PageStructureRequest,
	PageTextRequest,
	PromptContext,
	PromptSource,
	StructuredField,
)

__all__ = [
	"ALL_STRUCTURED_FIELDS",
	"ContextCollector",
	"ContextFragment",
	"PageContextFragment",
	"BrowserContextFragment",
	"TerminalContextFragment",
	"ImageContextFragment",
	"ContextPipeline",
	"BrowserAwarePageExtractor",
	"BrowserCandidateProvider",
	"build_chat_messages",
	"build_image_description_prompt",
	"build_extraction_summary_prompt",
	"build_system_prompt_for_nvda_assistant",
	"CandidateProvider",
	"CandidateExtractionContext",
	"ContentRequest",
	"ExtractionFacts",
	"ExtractionIntent",
	"ExtractionResult",
	"ExtractionSnapshot",
	"ExtractionStructure",
	"GenericCandidateProvider",
	"FocusedElementImageRequest",
	"FocusedElementTextRequest",
	"ForegroundImageRequest",
	"ImageCaptureSource",
	"ImageContext",
	"ImageContextCollector",
	"NavigatorImageRequest",
	"PageStructureRequest",
	"PageTextRequest",
	"PromptContext",
	"PromptSource",
	"StructuredField",
	"ExtractionStructureCollector",
	"ExtractionTextCollector",
	"PageExtractionError",
	"TerminalCandidateProvider",
	"TextEditorCandidateProvider",
	"TextAppCandidateProvider",
	"buildDefaultCandidateProviders",
]
