# -*- coding: utf-8 -*-
"""Static default configuration values for the NVDA AI assistant."""

DEFAULT_OLLAMA_MODEL = "gemma4:e2b"
DEFAULT_OLLAMA_URL = "http://127.0.0.1:11434"
DEFAULT_OLLAMA_CLI = "ollama"
DEFAULT_ENABLE_STREAMING = True
DEFAULT_ENABLE_PROGRESS_ANNOUNCEMENTS = True

DEFAULT_TIMEOUT_SECONDS = 450
DEFAULT_NUM_CTX = 131072
DEFAULT_KEEP_ALIVE = "5m"
DEFAULT_MAX_RETRIES = 2
DEFAULT_RETRY_BACKOFF_SECONDS = 0.75

DEFAULT_GENERATE_TEMPERATURE = 0.3
DEFAULT_GENERATE_TOP_K = 20
DEFAULT_GENERATE_TOP_P = 0.9
DEFAULT_GENERATE_PRESENCE_PENALTY = 0
